Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'rec_i3_owned_process.psm1') -Force
$children=@();$latePidPath=$null;$temporaryPaths=@()
try {
  $parentIdentity=[ordered]@{processId=100;parentProcessId=1;executablePath='C:\Windows\System32\cmd.exe';creationTimeUtc='2026-09-11T08:00:00.0000000Z';creationFileTimeUtc=1000L}
  $childIdentity=[ordered]@{processId=200;parentProcessId=100;executablePath='C:\Windows\System32\cmd.exe';creationTimeUtc='2026-09-11T08:00:00.0000100Z';creationFileTimeUtc=1100L}
  $first=[ordered]@{capturedAtFileTimeUtc=1200L;parents=@{200=100}}
  $confirm=[ordered]@{capturedAtFileTimeUtc=1300L;parents=@{200=100}}
  if(-not(Test-RecI3ObservedChildBinding $first $confirm $parentIdentity $childIdentity)){throw 'VALID_SNAPSHOT_CHILD_BINDING_REJECTED'}
  $replacement=[ordered]@{};foreach($k in $childIdentity.Keys){$replacement[$k]=$childIdentity[$k]};$replacement.creationFileTimeUtc=1201L
  try{$null=Test-RecI3ObservedChildBinding $first $confirm $parentIdentity $replacement;throw 'SNAPSHOT_CHILD_REPLACEMENT_ACCEPTED'}catch{if($_.Exception.Message-ceq'SNAPSHOT_CHILD_REPLACEMENT_ACCEPTED'){throw}}
  $olderChild=[ordered]@{};foreach($k in $childIdentity.Keys){$olderChild[$k]=$childIdentity[$k]};$olderChild.creationFileTimeUtc=999L
  try{$null=Test-RecI3ObservedChildBinding $first $confirm $parentIdentity $olderChild;throw 'OLDER_CHILD_REUSED_PARENT_ACCEPTED'}catch{if($_.Exception.Message-ceq'OLDER_CHILD_REUSED_PARENT_ACCEPTED'){throw}}
  $missing=[ordered]@{capturedAtFileTimeUtc=1300L;parents=@{}}
  try{$null=Test-RecI3ObservedChildBinding $first $missing $parentIdentity $childIdentity;throw 'MISSING_CONFIRMATION_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISSING_CONFIRMATION_ACCEPTED'){throw}}
  $postTerminateWaitFailure=New-RecI3TerminationExitUncertainResult $parentIdentity $parentIdentity $true $null 'WAIT_FAILED:synthetic'
  if(-not$postTerminateWaitFailure.terminationAttempted-or-not$postTerminateWaitFailure.terminationSucceeded-or-not$postTerminateWaitFailure.unknown-or$postTerminateWaitFailure.absenceObserved-or$postTerminateWaitFailure.state-cne'TERMINATION_EXIT_UNCERTAIN'-or$postTerminateWaitFailure.terminationError-cnotmatch'WAIT_FAILED'){throw 'POST_TERMINATION_WAIT_FAILURE_NOT_PRESERVED'}
  $bindingUnavailable=Stop-RecI3OwnedProcessClosure $null 0 1
  if($bindingUnavailable.cleanupCertain-or$bindingUnavailable.failures-cnotcontains'OWNED_PROCESS_BINDING_UNAVAILABLE'){throw 'BINDING_ACQUISITION_FAILURE_FALSE_PASS'}
  $budgetDeadline=100000L;foreach($now in @(10000L,50000L,99999L)){$step=Get-RecI3ShutdownBudgetStep $budgetDeadline $now 10000 1;if($step.exhausted-or-not$step.continueDiscovery-or$step.clampedWaitMilliseconds-le0){throw 'CONTINUOUS_ADDITION_BUDGET_PREMATURELY_EXHAUSTED'}}
  $exhausted=Get-RecI3ShutdownBudgetStep $budgetDeadline 100000L 10000 1;if(-not$exhausted.exhausted-or$exhausted.continueDiscovery-or$exhausted.clampedWaitMilliseconds-ne0){throw 'CONTINUOUS_ADDITION_BUDGET_DID_NOT_EXPIRE'}
  $ordinaryAdb='C:\Users\vinzer\AppData\Local\Android\Sdk\platform-tools\adb.exe'
  $localCacheAdb='C:\Users\vinzer\AppData\Local\Packages\OpenAI.Codex_2p2nqsd0c76g0\LocalCache\Local\Android\Sdk\platform-tools\adb.exe'
  $adbPin='B4A6B455702684652CCCF7B46258B29E653538904359A58FD4931CF3EF286B3F'
  foreach($adbView in @($ordinaryAdb,$localCacheAdb)){if(-not(Test-Path -LiteralPath $adbView -PathType Leaf)){throw "REAL_ADB_VIEW_MISSING:$adbView"};$sha=[Security.Cryptography.SHA256]::Create();$stream=[IO.File]::OpenRead($adbView);try{$actualPin=([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','')}finally{$stream.Dispose();$sha.Dispose()};if($actualPin-cne$adbPin){throw "REAL_ADB_PIN_MISMATCH:$adbView"}}
  $ordinaryBinding=Get-RecI3ExecutableFileBinding $ordinaryAdb $adbPin 'CONFIGURED_TARGET'
  $localCacheBinding=Get-RecI3ExecutableFileBinding $localCacheAdb $adbPin 'RETAINED_NATIVE_TARGET'
  if($ordinaryBinding.rawPath-cne$ordinaryAdb-or$localCacheBinding.rawPath-cne$localCacheAdb-or$ordinaryBinding.physicalId-cne$localCacheBinding.physicalId-or$ordinaryBinding.sha256-cne$adbPin-or$localCacheBinding.sha256-cne$adbPin){throw 'REAL_ADB_COHERENT_BINDING_INVALID'}
  if(-not(Test-RecI3ExecutableFileBinding $ordinaryBinding $localCacheBinding $adbPin)){throw 'REAL_ADB_ALIAS_BINDING_REJECTED'}
  $identityTime='2026-09-11T08:00:00.0000000Z';$identityFileTime=[DateTime]::ParseExact($identityTime,'o',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind).ToFileTimeUtc()
  $ordinaryIdentity=[ordered]@{processId=300;parentProcessId=1;executablePath=$ordinaryAdb;executableBinding=$ordinaryBinding;executablePhysicalId=$ordinaryBinding.physicalId;executableSha256=$ordinaryBinding.sha256;creationTimeUtc=$identityTime;creationFileTimeUtc=$identityFileTime}
  $localCacheIdentity=[ordered]@{processId=300;parentProcessId=1;executablePath=$localCacheAdb;executableBinding=$localCacheBinding;executablePhysicalId=$localCacheBinding.physicalId;executableSha256=$localCacheBinding.sha256;creationTimeUtc=$identityTime;creationFileTimeUtc=$identityFileTime}
  if(-not(Test-RecI3Identity $ordinaryIdentity $localCacheIdentity)){throw 'SAME_PHYSICAL_ADB_ALIAS_REJECTED'}
  $copyPath=Join-Path ([IO.Path]::GetTempPath()) ('dora-owned-file-copy-'+[Guid]::NewGuid().ToString('N')+'.exe');$temporaryPaths+=,$copyPath;Copy-Item -LiteralPath $ordinaryAdb -Destination $copyPath
  $copyBinding=Get-RecI3ExecutableFileBinding $copyPath $adbPin 'DIFFERENT_FILE_SAME_BYTES'
  try{$null=Test-RecI3ExecutableFileBinding $ordinaryBinding $copyBinding $adbPin;throw 'SAME_HASH_DIFFERENT_FILE_ACCEPTED'}catch{if($_.Exception.Message-ceq'SAME_HASH_DIFFERENT_FILE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_IDENTITY_MISMATCH'){throw}}
  try{$null=Get-RecI3ExecutableFileBinding $ordinaryAdb ('0'*64) 'WRONG_PIN';throw 'WRONG_PIN_ACCEPTED'}catch{if($_.Exception.Message-ceq'WRONG_PIN_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_PIN_MISMATCH'){throw}}
  try{$null=Get-RecI3ExecutableFileBinding ($ordinaryAdb+'.missing') $adbPin 'MISSING';throw 'MISSING_EXECUTABLE_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISSING_EXECUTABLE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_(MISSING|OPEN_FAILED)'){throw}}
  try{$null=Get-RecI3ExecutableFileBinding ([IO.Path]::GetDirectoryName($ordinaryAdb)) $null 'DIRECTORY';throw 'DIRECTORY_AS_EXECUTABLE_ACCEPTED'}catch{if($_.Exception.Message-ceq'DIRECTORY_AS_EXECUTABLE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_(NOT_REGULAR_FILE|OPEN_FAILED)'){throw}}
  $forgedId=[ordered]@{};foreach($k in $ordinaryBinding.Keys){$forgedId[$k]=$ordinaryBinding[$k]};$forgedId.physicalId='00000000:0000000000000000'
  try{$null=Test-RecI3ExecutableFileBinding $forgedId $localCacheBinding $adbPin;throw 'FORGED_FILE_ID_ACCEPTED'}catch{if($_.Exception.Message-ceq'FORGED_FILE_ID_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_DECLARATION_MISMATCH'){throw}}
  $forgedHash=[ordered]@{};foreach($k in $ordinaryBinding.Keys){$forgedHash[$k]=$ordinaryBinding[$k]};$forgedHash.sha256=('0'*64)
  try{$null=Test-RecI3ExecutableFileBinding $forgedHash $localCacheBinding $adbPin;throw 'FORGED_FILE_HASH_ACCEPTED'}catch{if($_.Exception.Message-ceq'FORGED_FILE_HASH_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_DECLARATION_MISMATCH'){throw}}
  $arrayHash=[ordered]@{};foreach($k in $ordinaryBinding.Keys){$arrayHash[$k]=$ordinaryBinding[$k]};$arrayHash.sha256=@($ordinaryBinding.sha256)
  try{$null=Test-RecI3ExecutableFileBinding $arrayHash $localCacheBinding $adbPin;throw 'ARRAY_FILE_HASH_ACCEPTED'}catch{if($_.Exception.Message-ceq'ARRAY_FILE_HASH_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_EXECUTABLE_DECLARATION_INVALID'){throw}}
  $wrongPid=[ordered]@{};foreach($k in $localCacheIdentity.Keys){$wrongPid[$k]=$localCacheIdentity[$k]};$wrongPid.processId=301
  try{$null=Test-RecI3Identity $ordinaryIdentity $wrongPid;throw 'PID_MISMATCH_ACCEPTED'}catch{if($_.Exception.Message-ceq'PID_MISMATCH_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_IDENTITY_MISMATCH'){throw}}
  $adjacentMicrosecond=[ordered]@{};foreach($k in $localCacheIdentity.Keys){$adjacentMicrosecond[$k]=$localCacheIdentity[$k]};$adjacentMicrosecond.creationTimeUtc='2026-09-11T08:00:00.0000010Z';$adjacentMicrosecond.creationFileTimeUtc=1010L
  try{$null=Test-RecI3Identity $ordinaryIdentity $adjacentMicrosecond;throw 'ADJACENT_MICROSECOND_ACCEPTED'}catch{if($_.Exception.Message-ceq'ADJACENT_MICROSECOND_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_IDENTITY_MISMATCH'){throw}}
  $receipt=[ordered]@{receiptPhase='COMPLETED';targetStarted=$true;targetProcessId=300;targetConfiguredPath=$ordinaryAdb;targetConfiguredBinding=$ordinaryBinding;targetNativeIdentity=$localCacheIdentity;targetNativeBinding=$localCacheBinding;targetBindingProof=[ordered]@{stage='CONFIGURED_TO_RETAINED_NATIVE_VERIFIED';verified=$true;error=$null};invocationArtifactPath=$ordinaryAdb;invocationArtifactBinding=$ordinaryBinding;rawExitValue=7;rawExitType='System.Int32';exitCode=7;targetExitCaptureError=$null;targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$false;laterAuditRequired=$true;rootAbsenceObserved=$true;failures=@('LATER_PROCESS_AUDIT_REQUIRED');results=@();state='TARGET_ROOT_EXITED_CLOSURE_UNAUDITED'};targetStdoutComplete=$true;targetStderrComplete=$true;targetStdoutReadError=$null;targetStderrReadError=$null;targetDisposeError=$null;firstFailure=$null;launchFailure=$null}
  $receipt=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json)
  if(-not(Confirm-RecI3ObservedTargetReceipt $receipt $ordinaryBinding $ordinaryBinding)){throw 'VALID_TARGET_RECEIPT_REJECTED'}
  $forgedReceipt=[ordered]@{};foreach($property in $receipt.PSObject.Properties){$forgedReceipt[$property.Name]=$property.Value};$forgedReceipt.targetNativeBinding=$copyBinding
  try{$null=Confirm-RecI3ObservedTargetReceipt $forgedReceipt $ordinaryBinding $ordinaryBinding;throw 'UNREAD_TARGET_RECEIPT_ACCEPTED'}catch{if($_.Exception.Message-ceq'UNREAD_TARGET_RECEIPT_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $arrayStarted=[ordered]@{};foreach($property in $receipt.PSObject.Properties){$arrayStarted[$property.Name]=$property.Value};$arrayStarted.targetStarted=@($true)
  try{$null=Confirm-RecI3ObservedTargetReceipt $arrayStarted $ordinaryBinding $ordinaryBinding;throw 'ARRAY_TARGET_STARTED_ACCEPTED'}catch{if($_.Exception.Message-ceq'ARRAY_TARGET_STARTED_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $falseClosure=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$falseClosure.targetCleanup.cleanupCertain=$true;$falseClosure.targetCleanup.laterAuditRequired=$false;$falseClosure.targetCleanup.failures=@();$falseClosure.targetCleanup.state='TARGET_EXITED_BEFORE_CLEANUP'
  try{$null=Confirm-RecI3ObservedTargetReceipt $falseClosure $ordinaryBinding $ordinaryBinding;throw 'ROOT_EXIT_PROMOTED_TO_CLOSURE_CERTAINTY'}catch{if($_.Exception.Message-ceq'ROOT_EXIT_PROMOTED_TO_CLOSURE_CERTAINTY'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $missingTime=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$missingTime.targetNativeIdentity.PSObject.Properties.Remove('creationTimeUtc')
  try{$null=Confirm-RecI3ObservedTargetReceipt $missingTime $ordinaryBinding $ordinaryBinding;throw 'MISSING_NATIVE_CREATION_TIME_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISSING_NATIVE_CREATION_TIME_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $notStartedSuccess=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$notStartedSuccess.targetStarted=$false
  try{$null=Confirm-RecI3ObservedTargetReceipt $notStartedSuccess $ordinaryBinding $ordinaryBinding;throw 'NOT_STARTED_SUCCESS_ACCEPTED'}catch{if($_.Exception.Message-ceq'NOT_STARTED_SUCCESS_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $stringBoolean=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$stringBoolean.targetCleanup.laterAuditRequired='true'
  try{$null=Confirm-RecI3ObservedTargetReceipt $stringBoolean $ordinaryBinding $ordinaryBinding;throw 'STRING_BOOLEAN_ACCEPTED'}catch{if($_.Exception.Message-ceq'STRING_BOOLEAN_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $missingOutcome=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$missingOutcome.rawExitValue=$null;$missingOutcome.rawExitType=$null;$missingOutcome.exitCode=$null;$missingOutcome.targetExitCaptureError=$null
  try{$null=Confirm-RecI3ObservedTargetReceipt $missingOutcome $ordinaryBinding $ordinaryBinding;throw 'MISSING_EXIT_OUTCOME_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISSING_EXIT_OUTCOME_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $uncertainResult=[ordered]@{capturedIdentity=$localCacheIdentity;freshIdentity=$null;terminationAttempted=$false;terminationSucceeded=$false;terminationError='SYNTHETIC_UNCERTAIN';absenceObserved=$false;replacementObserved=$false;unknown=$true;state='CLEANUP_UNCERTAIN';exitCode=$null;exitCodeCaptureError=$null}
  $contradictoryAggregate=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$contradictoryAggregate.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($uncertainResult);state='OWNED_CLOSURE_COMPLETE'}
  try{$null=Confirm-RecI3ObservedTargetReceipt ($contradictoryAggregate|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding;throw 'CONTRADICTORY_CLEANUP_AGGREGATE_ACCEPTED'}catch{if($_.Exception.Message-ceq'CONTRADICTORY_CLEANUP_AGGREGATE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $falseRootAbsence=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$falseRootAbsence.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$false;laterAuditRequired=$true;rootAbsenceObserved=$true;failures=@('SYNTHETIC_UNCERTAIN');results=@($uncertainResult);state='OWNED_CLOSURE_UNCERTAIN'}
  $missingBinding=($contradictoryAggregate|ConvertTo-Json -Depth 20|ConvertFrom-Json);$missingBinding.targetCleanup.cleanupCertain=$false;$missingBinding.targetCleanup.laterAuditRequired=$true;$missingBinding.targetCleanup.failures=@('SYNTHETIC_UNCERTAIN');$missingBinding.targetCleanup.state='OWNED_CLOSURE_UNCERTAIN';$missingBinding.targetCleanup.results[0].capturedIdentity.PSObject.Properties.Remove('executableBinding')
  try{$null=Confirm-RecI3ObservedTargetReceipt $missingBinding $ordinaryBinding $ordinaryBinding;throw 'CLEANUP_IDENTITY_WITHOUT_BINDING_ACCEPTED'}catch{if($_.Exception.Message-ceq'CLEANUP_IDENTITY_WITHOUT_BINDING_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $mismatchedFresh=($missingBinding|ConvertTo-Json -Depth 20|ConvertFrom-Json);$mismatchedFresh.targetCleanup.results[0].capturedIdentity=$localCacheIdentity;$mismatchedFresh.targetCleanup.results[0].freshIdentity=($localCacheIdentity|ConvertTo-Json -Depth 20|ConvertFrom-Json);$mismatchedFresh.targetCleanup.results[0].freshIdentity.processId=301;$mismatchedFresh.targetCleanup.results[0].terminationAttempted=$true
  try{$null=Confirm-RecI3ObservedTargetReceipt $mismatchedFresh $ordinaryBinding $ordinaryBinding;throw 'MISMATCHED_FRESH_CLEANUP_IDENTITY_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISMATCHED_FRESH_CLEANUP_IDENTITY_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $gracefulResult=[ordered]@{capturedIdentity=$localCacheIdentity;freshIdentity=$null;terminationAttempted=$false;terminationSucceeded=$false;terminationError=$null;absenceObserved=$true;replacementObserved=$false;unknown=$false;state='GRACEFUL_EXIT';exitCode=7;exitCodeCaptureError=$null}
  $validGraceful=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$validGraceful.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($gracefulResult);state='OWNED_CLOSURE_COMPLETE'};if(-not(Confirm-RecI3ObservedTargetReceipt ($validGraceful|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'VALID_GRACEFUL_CLEANUP_REJECTED'}
  $hiddenRootAbsence=($validGraceful|ConvertTo-Json -Depth 20|ConvertFrom-Json);$hiddenRootAbsence.targetCleanup.cleanupCertain=$false;$hiddenRootAbsence.targetCleanup.laterAuditRequired=$true;$hiddenRootAbsence.targetCleanup.rootAbsenceObserved=$false;$hiddenRootAbsence.targetCleanup.failures=@('SYNTHETIC_UNCERTAIN');$hiddenRootAbsence.targetCleanup.state='OWNED_CLOSURE_UNCERTAIN'
  $observedWithoutOutcome=($validGraceful|ConvertTo-Json -Depth 20|ConvertFrom-Json);$observedWithoutOutcome.targetCleanup.results[0].exitCode=$null
  $uncertainWithOutcome=($validGraceful|ConvertTo-Json -Depth 20|ConvertFrom-Json);$uncertainWithOutcome.targetCleanup.results[0].state='GRACEFUL_EXIT_CODE_UNCERTAIN'
  $unobservedWithOutcome=($falseRootAbsence|ConvertTo-Json -Depth 20|ConvertFrom-Json);$unobservedWithOutcome.targetCleanup.rootAbsenceObserved=$false;$unobservedWithOutcome.targetCleanup.results[0].exitCode=7
  $gracefulExitUnknown=($gracefulResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$gracefulExitUnknown.state='GRACEFUL_EXIT_CODE_UNCERTAIN';$gracefulExitUnknown.exitCode=$null;$gracefulExitUnknown.exitCodeCaptureError='SYNTHETIC_EXIT_CAPTURE_ERROR'
  $validGracefulExitUnknown=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$validGracefulExitUnknown.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($gracefulExitUnknown);state='OWNED_CLOSURE_COMPLETE'};if(-not(Confirm-RecI3ObservedTargetReceipt ($validGracefulExitUnknown|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'VALID_GRACEFUL_NULL_EXIT_REJECTED'}
  $attemptedResult=($gracefulResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$attemptedResult.freshIdentity=$localCacheIdentity;$attemptedResult.terminationAttempted=$true;$attemptedResult.terminationSucceeded=$true;$attemptedResult.state='TERMINATED';$attemptedResult.exitCode=125
  $validAttempted=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$validAttempted.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($attemptedResult);state='OWNED_CLOSURE_COMPLETE'};if(-not(Confirm-RecI3ObservedTargetReceipt ($validAttempted|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'VALID_ATTEMPTED_CLEANUP_REJECTED'}
  $terminatedExitUnknown=($attemptedResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$terminatedExitUnknown.state='TERMINATED_EXIT_CODE_UNCERTAIN';$terminatedExitUnknown.exitCode=$null;$terminatedExitUnknown.exitCodeCaptureError='SYNTHETIC_EXIT_CAPTURE_ERROR'
  $validTerminatedExitUnknown=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$validTerminatedExitUnknown.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($terminatedExitUnknown);state='OWNED_CLOSURE_COMPLETE'};if(-not(Confirm-RecI3ObservedTargetReceipt ($validTerminatedExitUnknown|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'VALID_TERMINATED_NULL_EXIT_REJECTED'}
  $terminationRaceExitUnknown=($attemptedResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$terminationRaceExitUnknown.terminationSucceeded=$false;$terminationRaceExitUnknown.terminationError='SYNTHETIC_EXITED_DURING_TERMINATION';$terminationRaceExitUnknown.state='EXITED_DURING_TERMINATION_EXIT_CODE_UNCERTAIN';$terminationRaceExitUnknown.exitCode=$null;$terminationRaceExitUnknown.exitCodeCaptureError='SYNTHETIC_EXIT_CAPTURE_ERROR'
  $validTerminationRaceExitUnknown=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$validTerminationRaceExitUnknown.targetCleanup=[ordered]@{rootIdentity=$localCacheIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($terminationRaceExitUnknown);state='OWNED_CLOSURE_COMPLETE'};if(-not(Confirm-RecI3ObservedTargetReceipt ($validTerminationRaceExitUnknown|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'VALID_TERMINATION_RACE_NULL_EXIT_REJECTED'}
  $wrapperIdentity=($localCacheIdentity|ConvertTo-Json -Depth 20|ConvertFrom-Json);$wrapperIdentity.processId=400
  $wrapperResult=($gracefulResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$wrapperResult.capturedIdentity=$wrapperIdentity
  $wrapperClosure=[ordered]@{rootIdentity=$wrapperIdentity;capturedCount=2;capturedAncestry=@($null,$null);unresolvedIdentities=@();snapshotPasses=4;stablePasses=2;shutdownBudgetMilliseconds=10000;budgetExhausted=$false;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($wrapperResult,$attemptedResult);state='OWNED_CLOSURE_COMPLETE'}
  $mapped=ConvertFrom-RecI3WrapperClosureTargetCleanup $localCacheIdentity ($wrapperClosure|ConvertTo-Json -Depth 20|ConvertFrom-Json);if(-not$mapped.cleanupCertain-or-not$mapped.rootAbsenceObserved-or$mapped.results.Count-ne1-or$mapped.rootIdentity.processId-ne300){throw 'EXACT_TARGET_CLEANUP_MAPPING_FAILED'}
  $descendantIdentity=($localCacheIdentity|ConvertTo-Json -Depth 20|ConvertFrom-Json);$descendantIdentity.processId=301
  $descendantUnknown=($uncertainResult|ConvertTo-Json -Depth 20|ConvertFrom-Json);$descendantUnknown.capturedIdentity=$descendantIdentity
  $unresolvedIdentity=($localCacheIdentity|ConvertTo-Json -Depth 20|ConvertFrom-Json);$unresolvedIdentity.processId=302
  $uncertainWrapperClosure=[ordered]@{rootIdentity=$wrapperIdentity;capturedCount=4;capturedAncestry=@($null,$null,$null,$null);unresolvedIdentities=@($unresolvedIdentity);snapshotPasses=4;stablePasses=1;shutdownBudgetMilliseconds=10000;budgetExhausted=$false;cleanupCertain=$false;laterAuditRequired=$true;rootAbsenceObserved=$true;failures=@('OWNED_INSTANCE_EXIT_UNCERTAIN:301','OWNED_DESCENDANT_CAPTURE_UNCERTAIN:302');results=@($wrapperResult,$attemptedResult,$descendantUnknown);state='OWNED_CLOSURE_UNCERTAIN'}
  $mappedUncertain=ConvertFrom-RecI3WrapperClosureTargetCleanup $localCacheIdentity ($uncertainWrapperClosure|ConvertTo-Json -Depth 20|ConvertFrom-Json);if($mappedUncertain.cleanupCertain-or-not$mappedUncertain.rootAbsenceObserved-or-not$mappedUncertain.laterAuditRequired-or$mappedUncertain.failures.Count-eq0){throw 'WRAPPER_CLOSURE_UNCERTAINTY_PROMOTED_TARGET_CERTAINTY'}
  $invalidWrapperClosure=($uncertainWrapperClosure|ConvertTo-Json -Depth 20|ConvertFrom-Json);$invalidWrapperClosure.results[2].capturedIdentity.PSObject.Properties.Remove('executableBinding')
  $mappedInvalid=ConvertFrom-RecI3WrapperClosureTargetCleanup $localCacheIdentity $invalidWrapperClosure;if($mappedInvalid.cleanupCertain-or-not$mappedInvalid.rootAbsenceObserved-or-not$mappedInvalid.laterAuditRequired-or$mappedInvalid.failures.Count-eq0){throw 'INVALID_WRAPPER_COVERAGE_PROMOTED_TARGET_CERTAINTY'}
  try{$null=Confirm-RecI3ObservedTargetReceipt $observedWithoutOutcome $ordinaryBinding $ordinaryBinding;throw 'OBSERVED_EXIT_WITHOUT_OUTCOME_ACCEPTED'}catch{if($_.Exception.Message-ceq'OBSERVED_EXIT_WITHOUT_OUTCOME_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  try{$null=Confirm-RecI3ObservedTargetReceipt $uncertainWithOutcome $ordinaryBinding $ordinaryBinding;throw 'UNCERTAIN_EXIT_WITH_CODE_ACCEPTED'}catch{if($_.Exception.Message-ceq'UNCERTAIN_EXIT_WITH_CODE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  try{$null=Confirm-RecI3ObservedTargetReceipt $unobservedWithOutcome $ordinaryBinding $ordinaryBinding;throw 'UNOBSERVED_EXIT_WITH_CODE_ACCEPTED'}catch{if($_.Exception.Message-ceq'UNOBSERVED_EXIT_WITH_CODE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  try{$null=Confirm-RecI3ObservedTargetReceipt $hiddenRootAbsence $ordinaryBinding $ordinaryBinding;throw 'ROOT_ABSENCE_HIDDEN_BY_AGGREGATE_ACCEPTED'}catch{if($_.Exception.Message-ceq'ROOT_ABSENCE_HIDDEN_BY_AGGREGATE_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  try{$null=Confirm-RecI3ObservedTargetReceipt ($falseRootAbsence|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding;throw 'ROOT_UNKNOWN_CLAIMED_ABSENT_ACCEPTED'}catch{if($_.Exception.Message-ceq'ROOT_UNKNOWN_CLAIMED_ABSENT_ACCEPTED'){throw};if($_.Exception.Message-cnotmatch'^OWNED_PROCESS_TARGET_RECEIPT_INVALID'){throw}}
  $unresolved=ConvertFrom-RecI3WrapperClosureTargetCleanup $localCacheIdentity ([ordered]@{rootIdentity=$wrapperIdentity;cleanupCertain=$true;laterAuditRequired=$false;rootAbsenceObserved=$true;failures=@();results=@($wrapperResult);state='OWNED_CLOSURE_COMPLETE'});if($unresolved.cleanupCertain-or$unresolved.rootAbsenceObserved-or-not$unresolved.laterAuditRequired-or$unresolved.results.Count-ne0-or$unresolved.failures-cnotcontains'TARGET_NOT_RECONCILED_IN_WRAPPER_CLOSURE'){throw 'WRAPPER_ROOT_FALSELY_SUBSTITUTED_FOR_TARGET'}
  $startedReceipt=($receipt|ConvertTo-Json -Depth 20|ConvertFrom-Json);$startedReceipt.receiptPhase='STARTED';foreach($name in @('rawExitValue','rawExitType','exitCode','targetExitCaptureError','targetCleanup','targetStdoutComplete','targetStderrComplete','targetStdoutReadError','targetStderrReadError','targetDisposeError','firstFailure','launchFailure')){$startedReceipt.$name=$null};if(-not(Confirm-RecI3ObservedTargetStartedReceipt ($startedReceipt|ConvertTo-Json -Depth 20|ConvertFrom-Json) $ordinaryBinding $ordinaryBinding)){throw 'STARTED_RECEIPT_ROUNDTRIP_FAILED'}
  $argv=@('plain','two words','', 'embedded"quote', 'C:\trailing slash\')
  $argvOutput=Join-Path ([IO.Path]::GetTempPath()) ('dora-owned-argv-'+[Guid]::NewGuid().ToString('N')+'.json');$temporaryPaths+=,$argvOutput
  $argvScript='import json, pathlib, sys; pathlib.Path(sys.argv[1]).write_text(json.dumps({"argv":sys.argv[2:]}))'
  $argvLine=ConvertTo-RecI3WindowsCommandLine (@('-c',$argvScript,$argvOutput)+$argv)
  $argvProcess=Start-Process -FilePath 'C:\Users\vinzer\.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe' -ArgumentList $argvLine -PassThru -WindowStyle Hidden;$children+=,$argvProcess;$argvProcess.WaitForExit(10000)|Out-Null
  $observedArgv=@((Get-Content -Raw -LiteralPath $argvOutput|ConvertFrom-Json).argv);if($observedArgv.Count-ne$argv.Count-or(Compare-Object -CaseSensitive $argv $observedArgv)){throw 'WINDOWS_NATIVE_ARGV_BOUNDARIES_LOST'}
  $p=Start-Process -FilePath $env:ComSpec -ArgumentList @('/d','/c','ping 127.0.0.1 -n 30 >nul') -PassThru -WindowStyle Hidden;$children+=,$p
  $b=New-RecI3OwnedProcessBinding $p
  $wrong=[ordered]@{};foreach($k in $b.capturedIdentity.Keys){$wrong[$k]=$b.capturedIdentity[$k]};$wrong.executablePath='C:\Windows\System32\notepad.exe'
  try{$null=Test-RecI3Identity $wrong $b.capturedIdentity;throw 'MISMATCH_ACCEPTED'}catch{if($_.Exception.Message-ceq'MISMATCH_ACCEPTED'){throw}}
  if($p.HasExited){throw 'MISMATCH_KILLED_CHILD'}
  $r=Stop-RecI3OwnedProcess $b 0 10000
  if($r.state-cne'TERMINATED'-or-not$r.terminationSucceeded-or-not$r.absenceObserved){throw 'EXACT_HANDLE_TERMINATION_FAILED'}
  $exitFailureProcess=Start-Process -FilePath $env:ComSpec -ArgumentList @('/d','/c','ping 127.0.0.1 -n 30 >nul') -PassThru -WindowStyle Hidden;$children+=,$exitFailureProcess
  $exitFailureBinding=New-RecI3OwnedProcessBinding $exitFailureProcess
  $exitFailureResult=Stop-RecI3OwnedProcess $exitFailureBinding 0 10000 { throw 'EXIT_CODE_FAILED:synthetic' }
  if($exitFailureResult.state-cne'TERMINATED_EXIT_CODE_UNCERTAIN'-or-not$exitFailureResult.terminationAttempted-or-not$exitFailureResult.terminationSucceeded-or-not$exitFailureResult.absenceObserved-or$exitFailureResult.unknown-or$exitFailureResult.exitCode-ne$null-or$exitFailureResult.exitCodeCaptureError-cnotmatch'EXIT_CODE_FAILED'){throw 'POST_TERMINATION_EXIT_CODE_FAILURE_NOT_PRESERVED'}
  $q=Start-Process -FilePath $env:ComSpec -ArgumentList @('/d','/c','exit 7') -PassThru -WindowStyle Hidden;$children+=,$q
  $qb=New-RecI3OwnedProcessBinding $q;$q.WaitForExit()
  $qr=Stop-RecI3OwnedProcess $qb 10 1000
  if($qr.state-cne'GRACEFUL_EXIT'-or$qr.exitCode-ne7-or$qr.terminationAttempted){throw 'ALREADY_EXITED_RESULT_INVALID'}
  $childPidPath=Join-Path ([IO.Path]::GetTempPath()) ('dora-owned-child-'+[Guid]::NewGuid().ToString('N')+'.txt')
  $nestedScript='$c=Start-Process -FilePath $env:ComSpec -ArgumentList @(''/d'',''/c'',''ping 127.0.0.1 -n 30 >nul'') -PassThru -WindowStyle Hidden;[IO.File]::WriteAllText('''+$childPidPath.Replace("'","''")+''',[string]$c.Id);Start-Sleep -Seconds 30'
  $encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($nestedScript));$root=Start-Process -FilePath (Join-Path $PSHOME 'powershell.exe') -ArgumentList @('-NoProfile','-NonInteractive','-EncodedCommand',$encoded) -PassThru -WindowStyle Hidden;$children+=,$root
  $deadline=[DateTime]::UtcNow.AddSeconds(5);while(-not(Test-Path -LiteralPath $childPidPath)-and[DateTime]::UtcNow-lt$deadline){Start-Sleep -Milliseconds 25};if(-not(Test-Path -LiteralPath $childPidPath)){throw 'NESTED_CHILD_NOT_STARTED'}
  $rootBinding=New-RecI3OwnedProcessBinding $root;$closure=Stop-RecI3OwnedProcessClosure $rootBinding 0 10000
  if(-not$closure.cleanupCertain-or$closure.capturedCount-lt2-or@($closure.capturedAncestry|Where-Object{$null-ne$_}).Count-lt1-or$closure.snapshotPasses-lt2-or$closure.stablePasses-lt2){throw "OWNED_DESCENDANT_CLOSURE_FAILED:$($closure|ConvertTo-Json -Depth 12 -Compress)"}
  $nestedPid=[int](Get-Content -Raw -LiteralPath $childPidPath);if(Get-Process -Id $nestedPid -ErrorAction SilentlyContinue){throw 'OWNED_DESCENDANT_REMAINS'};Remove-Item -LiteralPath $childPidPath -Force
  $latePidPath=Join-Path ([IO.Path]::GetTempPath()) ('dora-owned-late-child-'+[Guid]::NewGuid().ToString('N')+'.txt')
  $lateScript='Start-Sleep -Milliseconds 400;$c=Start-Process -FilePath $env:ComSpec -ArgumentList @(''/d'',''/c'',''ping 127.0.0.1 -n 30 >nul'') -PassThru -WindowStyle Hidden;[IO.File]::WriteAllText('''+$latePidPath.Replace("'","''")+''',[string]$c.Id);Start-Sleep -Seconds 30'
  $lateEncoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($lateScript));$lateRoot=Start-Process -FilePath (Join-Path $PSHOME 'powershell.exe') -ArgumentList @('-NoProfile','-NonInteractive','-EncodedCommand',$lateEncoded) -PassThru -WindowStyle Hidden;$children+=,$lateRoot
  $lateRootBinding=New-RecI3OwnedProcessBinding $lateRoot;$lateClosure=Stop-RecI3OwnedProcessClosure $lateRootBinding 1000 10000
  $lateDeadline=[DateTime]::UtcNow.AddSeconds(3);while(-not(Test-Path -LiteralPath $latePidPath)-and[DateTime]::UtcNow-lt$lateDeadline){Start-Sleep -Milliseconds 25};if(-not(Test-Path -LiteralPath $latePidPath)){throw 'LATE_CHILD_FIXTURE_DID_NOT_START'}
  $latePid=[int](Get-Content -Raw -LiteralPath $latePidPath);if(-not$lateClosure.cleanupCertain-or@($lateClosure.capturedAncestry|Where-Object{$null-ne$_-and$_.childIdentity.processId-eq$latePid}).Count-ne1-or(Get-Process -Id $latePid -ErrorAction SilentlyContinue)){throw "LATE_CHILD_DURING_CLEANUP_NOT_RECONCILED:$($lateClosure|ConvertTo-Json -Depth 12 -Compress)"};Remove-Item -LiteralPath $latePidPath -Force
  'PASS: exact retained handle identity, snapshot-bound descendants, mismatch rejection, termination, graceful race, and reconciled descendant closure'
} finally { foreach($c in $children){try{if(-not$c.HasExited){$c.Kill();$c.WaitForExit(5000)|Out-Null}}catch{};try{$c.Dispose()}catch{}};if($null-ne$latePidPath-and(Test-Path -LiteralPath $latePidPath)){try{$latePid=[int](Get-Content -Raw -LiteralPath $latePidPath);$lateChild=Get-Process -Id $latePid -ErrorAction SilentlyContinue;if($null-ne$lateChild){$lateChild.Kill();$lateChild.WaitForExit(5000)|Out-Null;$lateChild.Dispose()}}catch{};Remove-Item -LiteralPath $latePidPath -Force -ErrorAction SilentlyContinue};foreach($temporaryPath in $temporaryPaths){Remove-Item -LiteralPath $temporaryPath -Force -ErrorAction SilentlyContinue} }
