"""5.6C.2A: generated metadata/results only; never model, corpus or ADB."""
import copy
import importlib.util
import io
import json
from pathlib import Path
import tempfile
import unittest
from contextlib import redirect_stdout, contextmanager, ExitStack


def selected():
    return [{'sampleId': f'sample-{i:016x}', 'locale': 'ru' if i < 24 else 'en'}
            for i in range(48)]


def attempt(row):
    return {'caseId': row['sampleId'], 'locale': row['locale'], 'ordinal': 1,
            'state': 'SUCCEEDED', 'cleanup': 'VERIFIED', 'oomEvidence': [],
            'quality': {'raw': {'errors': 0, 'referenceTokens': 100},
                        'normalized': {'errors': 0, 'referenceTokens': 100}},
            'durationMicros': 1000000, 'inferenceMicros': 1000000,
            'coldLoadMicros': 100000, 'freshProcessContext': True,
            'windowStartMicros': 1000000, 'windowEndMicros': 2000000,
            'memory': [[1000000, 1000, 1000], [2000000, 1000, 1000]],
            'thermalWindowStartMicros': 1000000, 'thermalWindowEndMicros': 2000000,
            'thermal': [[1000000, 0], [2000000, 0]], 'endToEndMicros': 999999999}


@contextmanager
def synthetic_inputs():
    """Actual file verification against generated bytes; no controlled locations."""
    import run_alpha_asr_small_campaign as op
    import alpha_asr_small_campaign as c
    from unittest.mock import patch
    import hashlib
    from types import SimpleNamespace
    with tempfile.TemporaryDirectory() as td, ExitStack() as patches:
        repo = Path(td); (repo/'tools').mkdir(); docs = repo/'docs/evidence/poc-asr-001'; docs.mkdir(parents=True)
        root = repo/'acceptance'; root.mkdir(); runtime = repo/'runtime'; (runtime/'examples').mkdir(parents=True)
        work = repo/'work'; work.mkdir()
        (runtime/'examples/miniaudio.h').write_bytes(b'synthetic decoder')
        decoder = hashlib.sha256(b'synthetic decoder').hexdigest()
        rows = selected(); bindings = {}
        for i, row in enumerate(rows):
            audio = root/f'a-{i}'; ref = root/f'r-{i}'
            audio.write_bytes(f'synthetic audio {i}'.encode()); ref.write_bytes(f'synthetic ref {i}'.encode())
            row.update(audioSha256=op.file_sha(audio), referenceTextSha256=op.file_sha(ref), audioByteLength=audio.stat().st_size)
            bindings[row['sampleId']] = {'audio': str(audio), 'reference': str(ref)}
        docs_values = {'MANIFEST_SHA': (root/'materialized-manifest.json', {'samples': rows}),
            'TRANSFER_SHA': (root/'transfer-index.json', {'synthetic': 'transfer', 'manifestSha256': 'a'*64}),
            'FREEZE_SHA': (root/'pre-inference-freeze.json', {'synthetic': 'freeze', 'manifestSha256': 'a'*64}),
            'DECODING_SHA': (docs/'alpha-asr-decoding-profile-stage0-v0.1.json', {'synthetic': 'decoding'}),
            'PROTOCOL_SHA': (docs/'alpha-asr-measurement-protocol-stage0-v0.1.json', {'decoderSha256': decoder})}
        pins = {}
        for name, (path, value) in docs_values.items():
            path.write_bytes(c.canonical(value)); pins[name] = c.digest(value)
        gates = {'synthetic': 'resource'}; pins['GATES_SHA'] = c.digest(gates)
        (docs/'alpha-asr-small-evaluation-governance-stage0-v0.1.json').write_bytes(c.canonical({'resourceGates': gates}))
        model = repo/'ggml-small-q5_1.bin'; model.write_bytes(b'synthetic model')
        pins.update(MODEL_SHA=op.file_sha(model), MODEL_BYTES=model.stat().st_size)
        native = repo/'native'; native.write_bytes(b'synthetic native')
        (docs/'alpha-asr-campaign-stage0-v0.1.json').write_bytes(c.canonical({'runtime': {'nativeArtifacts': {
            'native': {'sha256': op.file_sha(native), 'bytes': native.stat().st_size}}}}))
        config = dict(operatorCommit='a'*40, acceptance=str(root), work=str(work), model=str(model),
                      native={'native': str(native)}, runtimeSource=str(runtime), bindings=bindings)
        patches.enter_context(patch.multiple(c, **pins))
        patches.enter_context(patch.object(op, '__file__', str(repo/'tools/run_alpha_asr_small_campaign.py')))
        patches.enter_context(patch.object(op, 'verify_repository'))
        patches.enter_context(patch('run_alpha_asr_campaign.require_private'))
        patches.enter_context(patch.object(op.subprocess, 'run', side_effect=lambda args, **kw:
            SimpleNamespace(returncode=0, stdout=(c.text.RUNTIME_COMMIT.encode() if 'rev-parse' in args else b''))))
        yield config, docs_values, repo


class SmallCampaignTests(unittest.TestCase):
    def setUp(self):
        self.assertIsNotNone(importlib.util.find_spec('alpha_asr_small_campaign'),
                             'SMALL evaluator has not been implemented')
        import alpha_asr_small_campaign as c
        self.c = c
        self.rows = selected()
        self.results = [attempt(r) for r in self.rows]

    def evaluate(self):
        return self.c.evaluate(self.c.profile(), self.rows, self.results, 'VERIFIED')

    def test_small_profile_acceptance(self):
        self.c.validate_profile(self.c.profile())
        self.assertEqual('dora-alpha-asr-small-eval-profile-v0.1', self.c.profile()['profileId'])
        self.assertEqual('PASS', self.evaluate()['resource'])

    def test_base_profile_rejected(self):
        import alpha_asr_eval_text_contract as old
        with self.assertRaises(ValueError): self.c.validate_profile(old.profile())

    def test_every_identity_drift_rejected(self):
        for key in ('selectedManifestSha256', 'transferIndexSha256', 'privateFreezeSha256',
                    'modelSha256', 'modelBytes', 'decodingProfileSha256',
                    'measurementProtocolSha256', 'resourceGateSha256', 'runtimeSourceCommit'):
            with self.subTest(key=key):
                p = self.c.profile(); p[key] = 1 if key == 'modelBytes' else '0' * 64
                with self.assertRaises(ValueError): self.c.validate_profile(p)

    def test_bool_and_extra_profile_fields_rejected(self):
        p = self.c.profile(); p['languageGates']['ru']['errors'] = True
        with self.assertRaises(ValueError): self.c.validate_profile(p)
        p = self.c.profile(); p['extra'] = 'secret'
        with self.assertRaises(ValueError): self.c.validate_profile(p)

    def test_normalizer_and_token_stream_parity(self):
        import alpha_asr_eval_text_contract as old
        for text in (' ONE two! ', 'Ёжик [шум] (тест) — 12', 'İ é\u0301 Ａ', '', 'a<q]b', '🦊\n中文'):
            value = self.c.prepare_case(self.c.profile(), self.rows[0], 'Ref Ё!', text)
            historical = old.prepare_case({'profile': old.profile(), 'caseId': self.rows[0]['sampleId'],
                'locale': 'ru', 'referenceText': 'Ref Ё!', 'hypothesisText': text})
            self.assertEqual(historical, value)

    def test_java_oracle_scoring_parity(self):
        from alpha_asr_campaign import Oracle
        import alpha_asr_eval_text_contract as old
        with tempfile.TemporaryDirectory() as td:
            oracle = Oracle(Path(td)); oracle.compile()
            for reference, hypothesis in [('ONE two', 'one extra two'), ('Ёжик здесь', ''), ('a b', 'a c')]:
                new = self.c.prepare_case(self.c.profile(), self.rows[0], reference, hypothesis)
                prior = old.prepare_case({'profile': old.profile(), 'caseId': self.rows[0]['sampleId'],
                    'locale': 'ru', 'referenceText': reference, 'hypothesisText': hypothesis})
                self.assertEqual(oracle.score(prior), oracle.score(new))

    def test_ru_integer_boundary(self):
        for r in self.results[:24]: r['quality']['normalized']['errors'] = 20
        self.assertEqual('PASS', self.evaluate()['quality'])
        self.results[0]['quality']['normalized']['errors'] += 1
        self.assertEqual('FAIL', self.evaluate()['quality'])

    def test_en_integer_boundary(self):
        for r in self.results[24:]: r['quality']['normalized']['errors'] = 18
        self.assertEqual('PASS', self.evaluate()['quality'])
        self.results[24]['quality']['normalized']['errors'] += 1
        self.assertEqual('FAIL', self.evaluate()['quality'])

    def test_complete_24_24_required(self):
        self.results.pop()
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', self.evaluate()['candidate'])
        self.assertNotEqual('PASS', self.evaluate()['resource'])

    def test_invalid_selection_rejected(self):
        for kind in ('count', 'locale', 'duplicate', 'order'):
            rows = selected()
            if kind == 'count': rows.pop()
            if kind == 'locale': rows[0]['locale'] = 'en'
            if kind == 'duplicate': rows[1] = rows[0]
            if kind == 'order': rows.reverse()
            with self.subTest(kind=kind), self.assertRaises(ValueError):
                self.c.evaluate(self.c.profile(), rows, self.results, 'VERIFIED')

    def test_result_order_locale_duplicate_rejected(self):
        for kind in ('order', 'locale', 'duplicate', 'ordinal'):
            results = copy.deepcopy(self.results)
            if kind == 'order': results[0], results[1] = results[1], results[0]
            if kind == 'locale': results[0]['locale'] = 'en'
            if kind == 'duplicate': results[1] = results[0]
            if kind == 'ordinal': results[0]['ordinal'] = 2
            with self.subTest(kind=kind), self.assertRaises(ValueError):
                self.c.evaluate(self.c.profile(), self.rows, results, 'VERIFIED')

    def test_weighted_rtf_exact_boundary(self):
        for i, r in enumerate(self.results):
            r['durationMicros'] = (i + 1) * 1000000
            r['inferenceMicros'] = 2 * r['durationMicros']
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['inferenceMicros'] += 1
        self.assertIn('RTF_WEIGHTED', self.evaluate()['resourceFailures'])

    def test_float_rounding_cannot_pass(self):
        for r in self.results:
            r['durationMicros'] = 2**54; r['inferenceMicros'] = 2**55
        self.results[0]['inferenceMicros'] += 1
        self.assertEqual('FAIL', self.evaluate()['resource'])

    def test_p95_rank46(self):
        for r in self.results[-3:]: r['inferenceMicros'] = 4000000
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[-3]['inferenceMicros'] += 1
        self.assertNotIn('RTF_P95', self.evaluate()['resourceFailures'])
        for r in self.results[-3:]: r['inferenceMicros'] = 4000001
        self.assertIn('RTF_P95', self.evaluate()['resourceFailures'])
        self.assertEqual(46, self.evaluate()['rtf']['p95Rank'])

    def test_maximum_rtf_boundary(self):
        self.results[0]['inferenceMicros'] = 6000000
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['inferenceMicros'] += 1
        self.assertIn('RTF_MAXIMUM', self.evaluate()['resourceFailures'])

    def test_cold_load_boundary(self):
        self.results[0]['coldLoadMicros'] = 15000000
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['coldLoadMicros'] += 1
        self.assertIn('COLD_LOAD', self.evaluate()['resourceFailures'])

    def test_pss_boundary(self):
        self.results[0]['memory'][0][1] = 1610612736
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['memory'][0][1] += 1
        self.assertIn('PSS', self.evaluate()['resourceFailures'])

    def test_heap_boundary_separate_from_pss(self):
        self.results[0]['memory'][0][1:] = [1610612736, 1342177280]
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['memory'][0][2] += 1
        self.assertIn('NATIVE_HEAP', self.evaluate()['resourceFailures'])

    def test_evidenced_oom_before_quality_completion(self):
        self.results = self.results[:1]; self.results[0]['state'] = 'FAILED'
        self.results[0]['quality'] = None
        self.results[0]['oomEvidence'] = [{'kind': 'OWNED_PROCESS_LMK', 'sha256': 'a' * 64}]
        out = self.evaluate()
        self.assertEqual('VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_RESOURCE_GATE', out['candidate'])
        self.assertEqual('NOT_EVALUABLE', out['quality'])

    def test_ambiguous_exit_is_not_oom(self):
        self.results = self.results[:1]; self.results[0]['state'] = 'FAILED'
        self.results[0]['quality'] = None
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', self.evaluate()['candidate'])
        self.assertNotIn('OOM', self.evaluate()['resourceFailures'])

    def test_thermal_none_to_moderate(self):
        for status in range(3):
            self.results[0]['thermal'][0][1] = status
            self.assertEqual('PASS', self.evaluate()['resource'])

    def test_thermal_severe_and_worse(self):
        self.results = self.results[:1]
        for status in range(3, 7):
            self.results[0]['thermal'][0][1] = status
            self.assertEqual('FAIL', self.evaluate()['resource'])
            self.assertEqual('NOT_EVALUABLE', self.evaluate()['quality'])

    def test_memory_gap_boundary_and_coverage(self):
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['memory'][-1][0] += 1
        self.assertEqual('NOT_EVALUABLE', self.evaluate()['resource'])
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', self.evaluate()['candidate'])

    def test_thermal_gap_boundary(self):
        self.results[0]['thermal'][-1][0] = 4000000
        self.assertEqual('PASS', self.evaluate()['resource'])
        self.results[0]['thermal'][-1][0] += 1
        self.assertEqual('NOT_EVALUABLE', self.evaluate()['resource'])

    def test_missing_telemetry(self):
        for key in ('memory', 'thermal'):
            results = copy.deepcopy(self.results); results[0][key] = []
            out = self.c.evaluate(self.c.profile(), self.rows, results, 'VERIFIED')
            self.assertEqual('NOT_EVALUABLE', out['resource'])
            self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', out['candidate'])

    def test_telemetry_edges_and_reversed_clock(self):
        for samples in ([[3000001, 10, 10], [3100001, 10, 10]], [[2000000, 10, 10], [1000000, 10, 10]]):
            self.results[0]['memory'] = samples
            self.assertNotEqual('PASS', self.evaluate()['resource'])

    def test_cleanup_failure_prevents_pass(self):
        self.results[0]['cleanup'] = 'BLOCKED'
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', self.evaluate()['candidate'])

    def test_fresh_context_required(self):
        self.results[0]['freshProcessContext'] = False
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', self.evaluate()['candidate'])

    def test_diagnostic_fields_do_not_gate(self):
        for r in self.results:
            r['endToEndMicros'] = 10**18; r['quality']['raw']['errors'] = 100000
        self.assertEqual('PASS / ACCEPTED_FOR_BOUNDED_ALPHA_ON_POCO_M5', self.evaluate()['candidate'])

    def test_disposition_table(self):
        expected = {(True, 'PASS', 'PASS'): 'PASS / ACCEPTED_FOR_BOUNDED_ALPHA_ON_POCO_M5',
            (True, 'FAIL', 'PASS'): 'VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_QUALITY_GATE',
            (True, 'PASS', 'FAIL'): 'VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_RESOURCE_GATE',
            (True, 'FAIL', 'FAIL'): 'VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_QUALITY_AND_RESOURCE_GATES',
            (False, 'NOT_EVALUABLE', 'FAIL'): 'VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_RESOURCE_GATE',
            (False, 'NOT_EVALUABLE', 'NOT_EVALUABLE'): 'INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE',
            (False, 'PASS', 'PASS'): 'INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE'}
        for args, verdict in expected.items(): self.assertEqual(verdict, self.c.disposition(*args))

    def test_execution_distinct_from_quality_failure(self):
        self.results[0]['quality']['normalized']['errors'] = 1000
        self.assertEqual('PASS / BOUNDED_SMALL_POCO_48_CAMPAIGN_COMPLETE', self.evaluate()['execution'])
        self.assertTrue(self.evaluate()['candidate'].startswith('VALID_FAIL'))

    def test_public_output_allowlist(self):
        self.results[0]['privateLocator'] = 'controlled:synthetic-secret'
        self.results[0]['text'] = 'SYNTHETIC_SECRET_TEXT'
        out = json.dumps(self.evaluate())
        for text in ('sample-', 'controlled:', 'SYNTHETIC_SECRET_TEXT'): self.assertNotIn(text, out)

    def test_noninteger_measurement_not_pass(self):
        for value in (True, 1.0, -1, None):
            self.results[0]['inferenceMicros'] = value
            self.assertNotEqual('PASS', self.evaluate()['resource'])

    def test_entrypoint_rejects_measured_cli_without_reading_paths(self):
        import run_alpha_asr_small_campaign as op
        stream = io.StringIO()
        with redirect_stdout(stream): result = op.main(['campaign', 'controlled:SECRET'])
        self.assertNotEqual(0, result)
        self.assertNotIn('SECRET', stream.getvalue())

    def test_document_identity_verification_and_tamper(self):
        import run_alpha_asr_small_campaign as op
        good = {'synthetic': 1}
        self.assertEqual(good, op.bound_json(self.c.canonical(good), self.c.digest(good)))
        with self.assertRaises(ValueError): op.bound_json(b'{"synthetic":2}', self.c.digest(good))
        with self.assertRaises(ValueError): op.bound_json(b'{"a":1,"a":1}', '0' * 64)

    def test_model_size_and_sha_are_both_required(self):
        import run_alpha_asr_small_campaign as op
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / 'synthetic'; p.write_bytes(b'generated')
            from alpha_asr_campaign import file_sha
            op.verify_file(p, 9, file_sha(p))
            with self.assertRaises(ValueError): op.verify_file(p, 10, file_sha(p))
            with self.assertRaises(ValueError): op.verify_file(p, 9, '0' * 64)

    def run_sequence(self, fail=None, bad_cleanup=False):
        import run_alpha_asr_small_campaign as op
        calls = []; retained = []
        class Driver:
            def warmup(inner): calls.append('warmup'); return 'VERIFIED'
            def case(inner, row, position):
                calls.append(position)
                r = attempt(row)
                if fail == 'exception': raise ValueError('synthetic-private-error')
                if fail == 'thermal': r['thermal'][0][1] = 3
                if fail == 'telemetry': r['memory'] = []
                if fail == 'quality': r['quality']['normalized']['errors'] = 1000
                return r
            def cleanup(inner): calls.append('cleanup'); return 'BLOCKED' if bad_cleanup else 'VERIFIED'
        class Journal:
            def records(inner): return retained
            def begin(inner, position, caseid, locale, ordinal, request):
                retained.append({'position': position, 'result': None})
            def finish(inner, position, result): retained[position - 1]['result'] = result
        def verify(): calls.append('verify')
        out = op.run_sequence(self.rows, Driver(), Journal(), verify)
        return out, calls, retained

    def test_operator_warmup_before_48_single_attempts(self):
        out, calls, retained = self.run_sequence()
        self.assertEqual(['verify', 'warmup', 'verify', 1], calls[:4])
        self.assertEqual(48, len(retained)); self.assertEqual(1, calls.count('warmup'))
        self.assertEqual(list(range(1, 49)), [v for v in calls if type(v) is int])
        self.assertTrue(out['candidate'].startswith('PASS'))

    def test_operator_exception_retained_without_retry(self):
        out, calls, retained = self.run_sequence('exception')
        self.assertEqual(1, len(retained)); self.assertEqual('FAILED', retained[0]['result']['state'])
        self.assertEqual('cleanup', calls[-1])
        self.assertTrue(out['candidate'].startswith('INCONCLUSIVE'))

    def test_operator_severe_stop_retains_decisive_failure(self):
        out, calls, retained = self.run_sequence('thermal')
        self.assertEqual(1, len(retained)); self.assertEqual('FAIL', out['resource'])
        self.assertTrue(out['candidate'].endswith('RESOURCE_GATE'))

    def test_operator_invalid_telemetry_stops(self):
        out, calls, retained = self.run_sequence('telemetry')
        self.assertEqual(1, len(retained)); self.assertTrue(out['candidate'].startswith('INCONCLUSIVE'))

    def test_operator_quality_fail_does_not_retry_or_change_order(self):
        out, calls, retained = self.run_sequence('quality')
        self.assertEqual(48, len(retained)); self.assertEqual('FAIL', out['quality'])
        self.assertTrue(out['execution'].startswith('PASS'))

    def test_operator_cleanup_failure_blocks_acceptance(self):
        out, calls, retained = self.run_sequence(bad_cleanup=True)
        self.assertEqual(48, len(retained)); self.assertTrue(out['candidate'].startswith('INCONCLUSIVE'))

    def test_operator_refuses_existing_attempt_journal(self):
        import run_alpha_asr_small_campaign as op
        class Journal:
            def records(self): return [{'state': 'RUNNING'}]
        with self.assertRaises(ValueError): op.run_sequence(self.rows, None, Journal(), lambda: None)

    def test_final_identity_drift_prevents_acceptance(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import Mock
        driver = Mock(); driver.warmup.return_value = 'VERIFIED'; driver.cleanup.return_value = 'VERIFIED'
        driver.case.side_effect = lambda row, position: attempt(row)
        journal = Mock(); journal.records.return_value = []
        verify = Mock(side_effect=[None] * 49 + [ValueError('drift')])
        out = op.run_sequence(self.rows, driver, journal, verify)
        self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE', out['candidate'])
        self.assertEqual('VERIFIED', out['cleanup'])

    def test_bad_partial_reader_still_finalizes_failed_attempt(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import Mock
        driver = Mock(); driver.warmup.return_value = 'VERIFIED'; driver.cleanup.return_value = 'VERIFIED'
        driver.case.side_effect = ValueError('failed'); driver.partial.side_effect = ValueError('bad metrics')
        journal = Mock(); journal.records.return_value = []
        out = op.run_sequence(self.rows, driver, journal, lambda: None)
        self.assertEqual(1, out['attemptCount']); journal.finish.assert_called_once()

    def test_malformed_metrics_preserve_decisive_thermal(self):
        import run_alpha_asr_small_campaign as op
        with tempfile.TemporaryDirectory() as td:
            p = Path(td); (p/'metrics.json').write_text('{bad')
            (p/'thermal.jsonl').write_text('{"monotonicSeconds":1.5,"status":3}\n{bad\n')
            r = op.read_attempt(p, self.rows[0], 'FAILED')
            self.assertIn('THERMAL_SEVERE', self.c.case_resources(r)[1])

    def test_evidenced_native_allocation_failure_is_retained(self):
        import run_alpha_asr_small_campaign as op
        with tempfile.TemporaryDirectory() as td:
            p = Path(td)
            (p/'native.stderr').write_bytes(b'libc++abi: terminating due to uncaught exception of type std::bad_alloc: std::bad_alloc\n')
            r = op.read_attempt(p, self.rows[0], 'FAILED')
            self.assertIn('OOM', self.c.case_resources(r)[1])
            (p/'native.stderr').write_bytes(b'process exited with signal 9\n')
            r = op.read_attempt(p, self.rows[0], 'FAILED')
            self.assertNotIn('OOM', self.c.case_resources(r)[1])

    def test_independent_decisive_observations_survive_missing_fields(self):
        r = self.results[0]; r['coldLoadMicros'] = 15000001; r['inferenceMicros'] = None
        self.assertIn('COLD_LOAD', self.evaluate()['resourceFailures'])
        r['oomEvidence'] = [{'kind': 'OWNED_PROCESS_LMK', 'sha256': 'a'*64}, {}]
        self.assertIn('OOM', self.evaluate()['resourceFailures'])

    def test_operator_invalid_quality_stops_before_second_attempt(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import Mock
        driver = Mock(); driver.warmup.return_value = 'VERIFIED'; driver.cleanup.return_value = 'VERIFIED'
        r = attempt(self.rows[0]); r['quality'] = {}
        driver.case.return_value = r
        journal = Mock(); journal.records.return_value = []
        out = op.run_sequence(self.rows, driver, journal, lambda: None)
        self.assertEqual(1, driver.case.call_count); self.assertEqual(1, out['attemptCount'])

    def test_journal_failure_retains_decisive_returned_observation(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import Mock
        driver = Mock(); driver.warmup.return_value = 'VERIFIED'; driver.cleanup.return_value = 'VERIFIED'
        r = attempt(self.rows[0]); r['thermal'][0][1] = 3; driver.case.return_value = r
        journal = Mock(); journal.records.return_value = []; journal.finish.side_effect = OSError('disk')
        out = op.run_sequence(self.rows, driver, journal, lambda: None)
        self.assertEqual('FAIL', out['resource']); self.assertEqual(1, out['attemptCount'])
        self.assertTrue(out['execution'].startswith('INCOMPLETE'))

    def test_warmup_safety_failure_is_not_a_measured_attempt(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import Mock
        driver = Mock(); driver.warmup.side_effect = ValueError('thermal'); driver.cleanup.return_value = 'VERIFIED'
        driver.safety_evidence.return_value = [{'thermal': [[1, 3]], 'oomEvidence': []}]
        journal = Mock(); journal.records.return_value = []
        out = op.run_sequence(self.rows, driver, journal, lambda: None)
        self.assertEqual('FAIL', out['resource']); self.assertEqual(0, out['attemptCount'])
        self.assertTrue(out['candidate'].endswith('RESOURCE_GATE'))

    def test_document_whole_digest_allows_cross_document_manifest_binding(self):
        import run_alpha_asr_small_campaign as op
        value = {'manifestSha256': 'a'*64, 'synthetic': 1}
        self.assertEqual(value, op.bound_json(self.c.canonical(value), self.c.digest(value)))
        sha = self.c.digest({'synthetic': 1})
        self.assertEqual({'synthetic': 1, 'manifestSha256': sha}, op.bound_json(
            self.c.canonical({'synthetic': 1, 'manifestSha256': sha}), sha, 'manifestSha256'))

    def test_real_input_verifier_accepts_generated_bound_inputs(self):
        import run_alpha_asr_small_campaign as op
        with synthetic_inputs() as (config, values, repo):
            rows, _, _ = op.verify_inputs(config)
            self.assertEqual(48, len(rows))

    def test_real_input_verifier_rejects_each_document_drift(self):
        import run_alpha_asr_small_campaign as op
        for name in ('MANIFEST_SHA', 'TRANSFER_SHA', 'FREEZE_SHA', 'DECODING_SHA', 'PROTOCOL_SHA'):
            with self.subTest(name=name), synthetic_inputs() as (config, values, repo):
                path, value = values[name]; value['changed'] = True; path.write_bytes(self.c.canonical(value))
                with self.assertRaises(ValueError): op.verify_inputs(config)

    def test_real_input_verifier_rejects_model_native_reference_audio_drift(self):
        import run_alpha_asr_small_campaign as op
        for kind in ('model', 'native', 'audio', 'reference', 'gates', 'decoder'):
            with self.subTest(kind=kind), synthetic_inputs() as (config, values, repo):
                path = (Path(config['model']) if kind == 'model' else
                        Path(config['native']['native']) if kind == 'native' else
                        repo/'docs/evidence/poc-asr-001/alpha-asr-small-evaluation-governance-stage0-v0.1.json' if kind == 'gates' else
                        repo/'runtime/examples/miniaudio.h' if kind == 'decoder' else
                        Path(config['bindings'][self.rows[0]['sampleId']][kind]))
                if kind == 'gates': path.write_text('{"resourceGates":{"changed":true}}')
                else: path.write_bytes(b'changed synthetic')
                with self.assertRaises(ValueError): op.verify_inputs(config)

    def test_runtime_head_and_dirty_state_rejected(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import patch
        from types import SimpleNamespace
        for bad in ('head', 'dirty'):
            with synthetic_inputs() as (config, values, repo):
                def command(args, **kw):
                    return SimpleNamespace(returncode=0, stdout=(b'wrong' if bad == 'head' else self.c.text.RUNTIME_COMMIT.encode())
                        if 'rev-parse' in args else b' M source')
                with patch.object(op.subprocess, 'run', side_effect=command), self.assertRaises(ValueError):
                    op.verify_inputs(config)

    def test_future_authorization_rejects_before_any_read(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import patch
        with patch.object(op, 'verify_inputs') as reader:
            with self.assertRaises(ValueError): op.campaign({'private': 'synthetic'}, '5.6C.2A')
            reader.assert_not_called()

    def test_repository_commit_and_operator_hash_checks(self):
        import run_alpha_asr_small_campaign as op
        from unittest.mock import patch
        from types import SimpleNamespace
        with tempfile.TemporaryDirectory() as td:
            repo = Path(td); doc = repo/'docs/evidence/poc-asr-001'; doc.mkdir(parents=True)
            tool = repo/'operator.py'; tool.write_bytes(b'synthetic operator')
            record = {'evaluationProfile': self.c.profile(), 'evaluationProfileSha256': self.c.digest(self.c.profile()),
                'operatorFiles': {'operator.py': {'sha256': op.file_sha(tool)}}, 'protectedHistoricalFiles': {}}
            (doc/'alpha-asr-small-campaign-operator-stage0-v0.1.json').write_bytes(self.c.canonical(record))
            def command(args, **kw):
                value = ('a'*40 if args[-1] == 'HEAD' else self.c.RECOVERY_COMMIT if args[-1] == 'HEAD^'
                         else 'chat/alpha-asr-runner-scope' if 'branch' in args else '')
                return SimpleNamespace(returncode=0, stdout=value.encode())
            with patch.object(op.subprocess, 'run', side_effect=command):
                op.verify_repository(repo, 'a'*40)
                with self.assertRaises(ValueError): op.verify_repository(repo, 'b'*40)
                tool.write_bytes(b'drift')
                with self.assertRaises(ValueError): op.verify_repository(repo, 'a'*40)

    def test_physical_device_guard_rejects_wrong_model_before_prepare(self):
        from alpha_asr_campaign_device import Device
        from unittest.mock import Mock
        d = Device('SYNTHETIC_NOT_EXECUTED', {}, 'a'*64)
        d.command = Mock(return_value=b'List of devices attached\nSYNTHETIC device\n')
        d.shell = Mock(return_value=b'WRONG')
        with self.assertRaisesRegex(ValueError, 'BLOCKED_WRONG_CAMPAIGN_DEVICE'): d.connect()
        self.assertFalse(d.owned)

    def test_partial_native_metrics_keep_cold_load_rejection(self):
        import run_alpha_asr_small_campaign as op
        with tempfile.TemporaryDirectory() as td:
            p = Path(td); (p/'metrics.json').write_text(json.dumps({'modelLoadElapsedMicros': 15000001,
                'inferenceElapsedMicros': None, 'sampleRate': 16000, 'decodedFrames': 16000}))
            result = op.read_attempt(p, self.rows[0], 'FAILED')
            self.assertIn('COLD_LOAD', self.c.case_resources(result)[1])

    def test_malformed_cleanup_keeps_decisive_thermal(self):
        import run_alpha_asr_small_campaign as op
        with tempfile.TemporaryDirectory() as td:
            p = Path(td); (p/'thermal.jsonl').write_text('{"monotonicSeconds":1,"status":3}\n')
            for invalid in ('[]', 'null', '{}', '{bad'):
                (p/'cleanup.json').write_text(invalid)
                result = op.read_attempt(p, self.rows[0], 'FAILED')
                self.assertIn('THERMAL_SEVERE', self.c.case_resources(result)[1])


if __name__ == '__main__': unittest.main()
