"""Generated bytes and fake devices only; no controlled corpus/model/ADB access."""
import copy
import datetime
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import sqlite3
import subprocess
import tempfile
import unittest
import wave
from contextlib import closing, contextmanager, ExitStack, redirect_stdout
from types import SimpleNamespace
from unittest.mock import patch

import alpha_asr_small_campaign as c
import run_alpha_asr_small_campaign as v1
import run_alpha_asr_small_campaign_v2 as v2
from test_alpha_asr_small_campaign_v2 import fixture, refresh, pins, AdmittedDate


def sha(raw): return hashlib.sha256(raw).hexdigest()


@contextmanager
def generated(op):
    with tempfile.TemporaryDirectory() as td, ExitStack() as stack:
        root=Path(td); repo=root/'repo'; (repo/'tools').mkdir(parents=True)
        public=repo/'docs/evidence/poc-asr-001'; public.mkdir(parents=True)
        acceptance=root/'acceptance'; materialized=acceptance/'materialized-5.6c11'
        runtime=root/'runtime'; (runtime/'examples').mkdir(parents=True)
        model=root/'ggml-small-q5_1.bin'; model.write_bytes(b'generated-small-model')
        (runtime/'examples/miniaudio.h').write_bytes(b'generated decoder')
        (runtime/'samples').mkdir(); (runtime/'samples/jfk.mp3').write_bytes(b'generated codec')
        native=root/'native'; native.mkdir()
        native_pins={}; native_paths={}
        for name in op.NATIVE_NAMES:
            p=native/name; p.write_bytes(('generated '+name).encode())
            native_pins[name]={'bytes':p.stat().st_size,'sha256':sha(p.read_bytes())}; native_paths[name]=str(p)
        decoding={'resolvedWhisperFullParams':{'ru':{'language':'ru'},'en':{'language':'en'}},'generatedFloat':0.5}
        protocol={'decoderSha256':sha(b'generated decoder')}; gates={'generated':'gates'}
        for name,value in [('alpha-asr-decoding-profile-stage0-v0.1.json',decoding),
                           ('alpha-asr-measurement-protocol-stage0-v0.1.json',protocol),
                           ('alpha-asr-small-evaluation-governance-stage0-v0.1.json',{'resourceGates':gates}),
                           ('alpha-asr-campaign-stage0-v0.1.json',{'runtime':{'nativeArtifacts':native_pins},'generatedFloat':0.5})]:
            (public/name).write_bytes(c.canonical(value))
        stack.enter_context(patch.multiple(c,MODEL_BYTES=model.stat().st_size,MODEL_SHA=sha(model.read_bytes()),
            DECODING_SHA=c.digest(decoding),PROTOCOL_SHA=c.digest(protocol),GATES_SHA=c.digest(gates)))
        docs=fixture()
        for i,(row,b) in enumerate(zip(docs[0]['samples'],docs[1]['bindings'])):
            audio=f'generated audio {i}'.encode(); reference=f'generated reference {i}'.encode()
            for kind,raw in [('audio',audio),('reference',reference)]:
                p=materialized/b[kind+'RelativePath']; p.parent.mkdir(parents=True,exist_ok=True); p.write_bytes(raw)
                b[kind+'Bytes']=len(raw); b[kind+'Sha256']=sha(raw)
            row.update(audioByteLength=len(audio),audioSha256=sha(audio),referenceTextSha256=sha(reference))
        refresh(docs,rebuild_transfer=True)
        for relative,value in zip(v2.METADATA_PATHS,docs):
            p=acceptance/relative; p.parent.mkdir(parents=True,exist_ok=True); p.write_bytes(c.canonical(value)+b'\n')
        stack.enter_context(patch.object(v2,'DOCUMENT_PINS',pins(docs)))
        stack.enter_context(patch.object(op,'__file__',str(repo/'tools/run_alpha_asr_small_campaign_v3.py')))
        stack.enter_context(patch.object(op,'verify_repository'))
        stack.enter_context(patch.object(op,'require_private'))
        stack.enter_context(patch.object(op,'require_model_storage'))
        stack.enter_context(patch.object(op.datetime,'date',AdmittedDate))
        def git(args,**kwargs):
            return subprocess.CompletedProcess(args,0,c.text.RUNTIME_COMMIT.encode() if args[-1]=='HEAD' else b'',b'')
        stack.enter_context(patch.object(op.subprocess,'run',side_effect=git))
        config=dict(operatorCommit='a'*40,acceptance=str(acceptance),work=str(root/'work'),model=str(model),
                    native=native_paths,runtimeSource=str(runtime),adb='GENERATED_ADB_NEVER_EXECUTED')
        yield SimpleNamespace(config=config,repo=repo,root=root,docs=docs,decoding=decoding,public=public)


class FakeOracle:
    instances=[]
    def __init__(self,path): self.scores=[]; self.instances.append(self)
    def compile(self): pass
    def score(self,prepared):
        self.scores.append(prepared['caseId'])
        return {k:dict(substitutions=0,deletions=0,insertions=0,referenceTokens=100) for k in ('raw','normalized')}


class FakeDevice:
    instances=[]
    failure=None
    def __init__(self,*args):
        self.calls=[]; self.cleanup_calls=0; self.connected=0; self.instances.append(self)
    def connect(self): self.connected+=1; return {'thermalStatus':0}
    def prepare(self): pass
    def profile(self,locale): return {'language':locale}
    def execute(self,audio,locale,destination,mode='infer'):
        destination=Path(destination); name=destination.name
        self.calls.append((name,mode,locale))
        destination.mkdir(parents=True,exist_ok=False)
        corpus=name.isdigit(); frames=16000
        if name=='warmup':
            with wave.open(str(audio),'rb') as sound:
                assert sound.getnframes()==48000 and sound.getframerate()==16000
                assert sound.getnchannels()==1 and sound.getsampwidth()==2
                assert sound.readframes(48000)==b'\0'*96000
            frames=48000
        if corpus:
            with closing(sqlite3.connect(destination.parents[1]/'attempts.sqlite')) as db:
                rows=db.execute('SELECT id,ordinal,state FROM attempts ORDER BY id').fetchall()
            assert rows[-1]==(int(name),1,'RUNNING'), 'Journal must precede backend'
        metrics=dict(nativeCode=0,decodedFrames=frames,sampleRate=16000,inferenceElapsedMicros=1000000,
                     modelLoadElapsedMicros=100000,measurementStartMicros=1000000,measurementEndMicros=2000000)
        (destination/'metrics.json').write_bytes(c.canonical(metrics))
        (destination/'memory.csv').write_text('1000000,1000,1000\n2000000,1000,1000\n')
        (destination/'thermal.jsonl').write_text('{"monotonicSeconds":1,"status":0}\n{"monotonicSeconds":2,"status":0}\n')
        (destination/'cleanup.json').write_text('{"status":"VERIFIED"}')
        (destination/'hypothesis.txt').write_text('generated hypothesis')
        if self.failure=='invalid' and corpus: (destination/'memory.csv').write_text('invalid')
        if self.failure=='partial' and corpus:
            (destination/'thermal.jsonl').write_text('{"monotonicSeconds":1,"status":3}\n')
            raise ValueError('GENERATED_BACKEND_FAILURE')
        if self.failure=='ambiguous' and corpus: raise ValueError('GENERATED_BACKEND_FAILURE')
        if self.failure=='warmup' and name=='warmup': raise ValueError('GENERATED_WARMUP_FAILURE')
        return {'metrics':metrics,'thermal':{'maximum':0}}
    def cleanup(self): self.cleanup_calls+=1; return 'VERIFIED'


class ExecutionSuccessorTests(unittest.TestCase):
    def setUp(self):
        self.assertIsNotNone(importlib.util.find_spec('run_alpha_asr_small_campaign_v3'), 'Execution successor is not implemented')
        import run_alpha_asr_small_campaign_v3 as op
        self.op=op; FakeDevice.instances=[]; FakeOracle.instances=[]; FakeDevice.failure=None

    @contextmanager
    def campaign_fixture(self):
        with generated(self.op) as env,patch.object(self.op,'Device',FakeDevice),patch.object(self.op,'Oracle',FakeOracle), \
             patch.object(v1,'verify_inputs',side_effect=AssertionError('Broken v1 verifier')), \
             patch.object(v1,'campaign',side_effect=AssertionError('Historical campaign')):
            yield env

    def test_exact_v2_composition_and_derived_48_bindings(self):
        with generated(self.op) as env,patch.object(v2,'bind_metadata',wraps=v2.bind_metadata) as binder:
            result=self.op.verify_inputs(env.config)
            self.assertEqual(1,binder.call_count)
            self.assertEqual(env.docs[0]['samples'],result.rows)
            self.assertEqual(48,len(result.cases))
            for row,b in zip(result.rows,env.docs[1]['bindings']):
                case=result.cases[row['sampleId']]
                self.assertEqual(Path(env.config['acceptance'])/'materialized-5.6c11'/b['audioRelativePath'],case.audio)
                self.assertEqual(Path(env.config['acceptance'])/'materialized-5.6c11'/b['referenceRelativePath'],case.reference)

    def test_config_bindings_unknown_keys_rejected_before_reads(self):
        for key in ('bindings','selectionSha256','modelSha256','operatorId','unknown'):
            with self.subTest(key=key),patch.object(Path,'read_bytes',side_effect=AssertionError('No reads')):
                with self.assertRaisesRegex(ValueError,'CONFIG'):
                    self.op.verify_inputs({key:{}})

    def test_wrong_missing_old_authorization_before_paths(self):
        for token in (None,'','OWNER_AUTHORIZED_5.6C.2B','OWNER_AUTHORIZED_5.6C.2A.2'):
            with self.subTest(token=token),patch.object(Path,'read_bytes',side_effect=AssertionError('No reads')), \
                 patch.object(self.op,'verify_inputs',side_effect=AssertionError('No precheck')), \
                 self.assertRaisesRegex(ValueError,'NOT_AUTHORIZED'):
                self.op.campaign({},token)

    def test_cli_is_information_only(self):
        with patch.object(Path,'read_bytes',side_effect=AssertionError('No reads')),redirect_stdout(io.StringIO()) as output:
            self.assertEqual(2,self.op.main(['campaign','private-path']))
        self.assertNotIn('private-path',output.getvalue())

    def test_metadata_identity_drift_all_four(self):
        for relative in v2.METADATA_PATHS:
            with self.subTest(document=relative),generated(self.op) as env:
                (Path(env.config['acceptance'])/relative).write_bytes(b'{}')
                with patch.object(self.op,'verify_case_files',side_effect=AssertionError('No content')):
                    with self.assertRaises(ValueError): self.op.verify_inputs(env.config)

    def test_content_size_and_sha_mismatch(self):
        for kind in ('audio','reference'):
            for mutation in ('size','sha'):
                with self.subTest(kind=kind,mutation=mutation),generated(self.op) as env:
                    p=Path(env.config['acceptance'])/'materialized-5.6c11'/env.docs[1]['bindings'][0][kind+'RelativePath']
                    raw=p.read_bytes(); p.write_bytes(b'x'*(len(raw)+(mutation=='size')))
                    with self.assertRaisesRegex(ValueError,'FILE_IDENTITY'): self.op.verify_inputs(env.config)

    def test_model_name_bytes_sha_mismatch(self):
        for kind in ('name','bytes','sha'):
            with self.subTest(kind=kind),generated(self.op) as env:
                p=Path(env.config['model']); raw=p.read_bytes()
                if kind=='name':
                    other=p.with_name('wrong.bin'); other.write_bytes(raw); env.config['model']=str(other)
                else: p.write_bytes(b'x'*(len(raw)+(kind=='bytes')))
                with self.assertRaises(ValueError): self.op.verify_inputs(env.config)

    def test_native_mismatch_and_unknown_artifact(self):
        for kind in ('bytes','keys'):
            with self.subTest(kind=kind),generated(self.op) as env:
                if kind=='bytes': Path(next(iter(env.config['native'].values()))).write_bytes(b'bad')
                else: env.config['native']['extra']='unused'
                with self.assertRaises(ValueError): self.op.verify_inputs(env.config)

    def test_runtime_commit_and_dirty(self):
        for kind in ('commit','dirty'):
            with self.subTest(kind=kind),generated(self.op) as env:
                def git(args,**kwargs):
                    value=(b'wrong' if kind=='commit' else c.text.RUNTIME_COMMIT.encode()) if args[-1]=='HEAD' else b' M source'
                    return subprocess.CompletedProcess(args,0,value,b'')
                with patch.object(self.op.subprocess,'run',side_effect=git),self.assertRaisesRegex(ValueError,'RUNTIME'):
                    self.op.verify_inputs(env.config)

    def test_decoding_protocol_and_gates_mismatch(self):
        for name in ('alpha-asr-decoding-profile-stage0-v0.1.json','alpha-asr-measurement-protocol-stage0-v0.1.json',
                     'alpha-asr-small-evaluation-governance-stage0-v0.1.json'):
            with self.subTest(name=name),generated(self.op) as env:
                (env.public/name).write_bytes(c.canonical({'resourceGates':{'changed':1}}))
                with self.assertRaises(ValueError): self.op.verify_inputs(env.config)

    def test_decoder_identity_mismatch(self):
        with generated(self.op) as env:
            (Path(env.config['runtimeSource'])/'examples/miniaudio.h').write_bytes(b'bad')
            with self.assertRaises(ValueError): self.op.verify_inputs(env.config)

    def test_work_cannot_overlap_acceptance(self):
        with generated(self.op) as env:
            env.config['work']=str(Path(env.config['acceptance'])/'work')
            with self.assertRaisesRegex(ValueError,'WORK_STORAGE'): self.op.verify_inputs(env.config)

    def test_content_symlink_rejected_before_use(self):
        with generated(self.op) as env:
            with patch.object(Path,'is_symlink',return_value=True),self.assertRaises(ValueError):
                self.op.verify_inputs(env.config)

    def test_retention_stops_before_metadata(self):
        class Expired(datetime.date):
            @classmethod
            def today(cls): return cls(2026,10,26)
        with generated(self.op) as env,patch.object(self.op.datetime,'date',Expired), \
             patch.object(v2,'bind_metadata',side_effect=AssertionError('No metadata')),self.assertRaisesRegex(ValueError,'RETENTION'):
            self.op.verify_inputs(env.config)

    def test_complete_campaign_is_one_shot_and_journal_precedes_backend(self):
        with self.campaign_fixture() as env:
            result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual('PASS / ACCEPTED_FOR_BOUNDED_ALPHA_ON_POCO_M5',result['candidate'])
            self.assertEqual(48,result['attemptCount'])
            device=FakeDevice.instances[0]; oracle=FakeOracle.instances[0]
            self.assertEqual(1,device.connected); self.assertEqual(1,device.cleanup_calls)
            self.assertEqual([('codec','decode','en'),('warmup','infer','en')],device.calls[:2])
            self.assertEqual(50,len(device.calls)); self.assertEqual(48,len(oracle.scores))
            self.assertEqual([r['sampleId'] for r in env.docs[0]['samples']],oracle.scores)
            work=Path(env.config['work']); terminal=(work/'terminal-aggregate.json').read_bytes()
            with closing(sqlite3.connect(work/'attempts.sqlite')) as db:
                rows=db.execute('SELECT ordinal,state FROM attempts').fetchall()
            self.assertEqual([(1,'FINISHED')]*48,rows)
            with self.assertRaisesRegex(ValueError,'EXISTING_CAMPAIGN'): self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(1,len(FakeDevice.instances)); self.assertEqual(terminal,(work/'terminal-aggregate.json').read_bytes())

    def test_existing_marker_blocks_device(self):
        with self.campaign_fixture() as env:
            work=Path(env.config['work']); work.mkdir(); (work/'campaign-started.json').write_bytes(b'prior')
            with self.assertRaisesRegex(ValueError,'EXISTING_CAMPAIGN'): self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual([],FakeDevice.instances); self.assertFalse((work/'attempts.sqlite').exists())

    def test_existing_running_or_finished_journal_blocks(self):
        for finished in (False,True):
            with self.subTest(finished=finished),self.campaign_fixture() as env:
                work=Path(env.config['work']); work.mkdir(); journal=v1.Journal(work/'attempts.sqlite')
                row=env.docs[0]['samples'][0]; journal.begin(1,row['sampleId'],row['locale'],1,{})
                if finished: journal.finish(1,{'state':'FAILED'})
                journal.close()
                with self.assertRaisesRegex(ValueError,'EXISTING_CAMPAIGN'): self.op.campaign(env.config,self.op.AUTHORIZATION)
                self.assertEqual([],FakeDevice.instances); self.assertFalse((work/'campaign-started.json').exists())

    def test_invalid_case_stops_without_retry_and_cleans(self):
        with self.campaign_fixture() as env:
            FakeDevice.failure='invalid'; result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(1,result['attemptCount']); self.assertEqual(3,len(FakeDevice.instances[0].calls))
            self.assertEqual(1,FakeDevice.instances[0].cleanup_calls)
            self.assertEqual('NOT_EVALUABLE',result['resource'])

    def test_partial_decisive_resource_failure_preserved(self):
        with self.campaign_fixture() as env:
            FakeDevice.failure='partial'; result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(1,result['attemptCount']); self.assertIn('THERMAL_SEVERE',result['resourceFailures'])
            self.assertEqual('VALID_FAIL / REJECTED_FOR_BOUNDED_ALPHA_RESOURCE_GATE',result['candidate'])
            self.assertEqual(1,FakeDevice.instances[0].cleanup_calls)

    def test_ambiguous_backend_failure_does_not_invent_oom(self):
        with self.campaign_fixture() as env:
            FakeDevice.failure='ambiguous'; result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(1,result['attemptCount']); self.assertNotIn('OOM',result['resourceFailures'])
            self.assertEqual('INCONCLUSIVE / CAMPAIGN_EVIDENCE_INCOMPLETE',result['candidate'])

    def test_warmup_failure_no_case_no_quality_and_cleanup(self):
        with self.campaign_fixture() as env:
            FakeDevice.failure='warmup'; result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(0,result['attemptCount']); self.assertEqual([],FakeOracle.instances[0].scores)
            self.assertEqual(2,len(FakeDevice.instances[0].calls)); self.assertEqual(1,FakeDevice.instances[0].cleanup_calls)

    def test_case_identity_reverified_after_precheck(self):
        with generated(self.op) as env:
            inputs=self.op.verify_inputs(env.config); work=Path(env.config['work']); work.mkdir()
            driver=self.op.SmallDriver(env.config,FakeDevice(),inputs.decoding,FakeOracle(work),inputs)
            first=inputs.rows[0]; inputs.cases[first['sampleId']].audio.write_bytes(b'changed')
            with self.assertRaisesRegex(ValueError,'FILE_IDENTITY'): driver.case(first,1)
            self.assertEqual([],driver.device.calls)

    def test_case_row_and_position_cannot_substitute(self):
        with generated(self.op) as env:
            inputs=self.op.verify_inputs(env.config)
            driver=self.op.SmallDriver(env.config,FakeDevice(),inputs.decoding,FakeOracle(Path(env.config['work'])),inputs)
            for row,pos in [(inputs.rows[1],1),(dict(inputs.rows[0],locale='en'),1)]:
                with self.assertRaisesRegex(ValueError,'CASE_BINDING'): driver.case(row,pos)
            self.assertEqual([],driver.device.calls)

    def test_caller_config_change_cannot_replace_case(self):
        with generated(self.op) as env:
            inputs=self.op.verify_inputs(env.config)
            driver=self.op.SmallDriver(env.config,FakeDevice(),inputs.decoding,FakeOracle(Path(env.config['work'])),inputs)
            env.config['bindings']={'override':'elsewhere'}; env.config['acceptance']='elsewhere'
            self.assertNotIn('bindings',driver.config)
            self.assertEqual(Path(env.config['work']),driver.work)
            self.assertEqual(inputs.cases[inputs.rows[0]['sampleId']].audio,driver.inputs.cases[inputs.rows[0]['sampleId']].audio)

    def test_final_reverification_failure_prevents_pass(self):
        with self.campaign_fixture() as env:
            real=self.op.verify_inputs; calls=0
            def verify(config):
                nonlocal calls
                calls+=1
                if calls==51: raise ValueError('FINAL_DRIFT')
                return real(config)
            with patch.object(self.op,'verify_inputs',side_effect=verify): result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(48,result['attemptCount']); self.assertEqual('NOT_EVALUABLE',result['resource'])
            self.assertEqual(1,FakeDevice.instances[0].cleanup_calls)

    def test_setup_failure_retains_marker_and_terminal(self):
        with self.campaign_fixture() as env,patch.object(FakeOracle,'compile',side_effect=ValueError('GENERATED')):
            result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(0,result['attemptCount']); self.assertFalse(FakeDevice.instances)
            self.assertTrue((Path(env.config['work'])/'terminal-aggregate.json').is_file())
            self.assertTrue((Path(env.config['work'])/'campaign-started.json').is_file())

    def test_cleanup_failure_is_not_pass(self):
        with self.campaign_fixture() as env,patch.object(FakeDevice,'cleanup',side_effect=ValueError('GENERATED')):
            result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual('UNVERIFIED',result['cleanup']); self.assertNotEqual('PASS',result['resource'])

    def test_quality_failure_never_retries(self):
        def reject(oracle,prepared):
            oracle.scores.append(prepared['caseId'])
            return {k:dict(substitutions=100,deletions=0,insertions=0,referenceTokens=100) for k in ('raw','normalized')}
        with self.campaign_fixture() as env,patch.object(FakeOracle,'score',reject):
            result=self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual('FAIL',result['quality']); self.assertEqual(48,result['attemptCount'])
            self.assertEqual(50,len(FakeDevice.instances[0].calls))
            self.assertEqual(48,len(set(FakeOracle.instances[0].scores)))

    def test_terminal_write_failure_is_not_retried(self):
        with self.campaign_fixture() as env:
            FakeDevice.failure='invalid'; real=self.op.save_new; writes=[]
            def save(path,value):
                if Path(path).name=='terminal-aggregate.json':
                    writes.append(path); raise OSError('GENERATED_WRITE_FAILURE')
                return real(path,value)
            with patch.object(self.op,'save_new',side_effect=save),self.assertRaises(OSError):
                self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual(1,len(writes)); self.assertEqual(1,FakeDevice.instances[0].cleanup_calls)

    def test_precheck_failure_prevents_device_construction(self):
        with self.campaign_fixture() as env:
            Path(env.config['model']).write_bytes(b'bad')
            with self.assertRaises(ValueError): self.op.campaign(env.config,self.op.AUTHORIZATION)
            self.assertEqual([],FakeDevice.instances)
            self.assertFalse((Path(env.config['work'])/'campaign-started.json').exists())

    def test_missing_model_acl_fails_closed(self):
        # Synthetic nonexistent storage; no actual model/store is inspected.
        with tempfile.TemporaryDirectory() as td,patch.dict(os.environ,{'LOCALAPPDATA':td}):
            with self.assertRaisesRegex(ValueError,'MODEL_STORAGE_ACL'):
                self.op.require_model_storage(Path(td)/'DORA/model-storage/generated-store/missing.bin',Path(td)/'repo')

    def test_model_storage_uses_admitted_store_acl_boundary(self):
        with tempfile.TemporaryDirectory() as td,patch.dict(os.environ,{'LOCALAPPDATA':td}):
            store=Path(td)/'DORA/model-storage/generated-store'; model=store/'ggml-small-q5_1.bin'
            def acl(args,**kwargs):
                # 5.6A.1 protects the store and its files; ancestor ACLs are not its authority.
                checked=Path(kwargs['env']['DORA_MODEL_CHECK_PATH'])
                return subprocess.CompletedProcess(args,0 if checked in (store,model) else 2,b'',b'')
            with patch.object(self.op.subprocess,'run',side_effect=acl):
                self.op.require_model_storage(model,Path(td)/'repo')

    def test_private_acl_unreadable_stops_acceptance_work_and_content(self):
        run=subprocess.run
        for relative in ('acceptance','work','acceptance/audio.mp3','acceptance/reference.txt'):
            with self.subTest(relative=relative),tempfile.TemporaryDirectory() as td:
                root=Path(td)/'DORA/private'; target=root/relative
                target.parent.mkdir(parents=True,exist_ok=True)
                if target.suffix: target.write_bytes(b'generated')
                else: target.mkdir()
                def unreadable(args,**kwargs):
                    args=list(args)
                    args[-1]="function Get-Acl { Write-Error 'SYNTHETIC_ACL_UNREADABLE' }; "+args[-1]
                    return run(args,**kwargs)
                with patch.dict(os.environ,LOCALAPPDATA=td),patch.object(self.op.subprocess,'run',side_effect=unreadable), \
                     self.assertRaisesRegex(ValueError,'PRIVATE_STORAGE_ACL_INVALID'):
                    self.op.require_private(target,Path(td)/'repo')

    def test_private_acl_owner_only_allows_new_work_but_not_foreign_or_empty_acl(self):
        run=subprocess.run
        with tempfile.TemporaryDirectory() as td,patch.dict(os.environ,LOCALAPPDATA=td):
            root=Path(td)/'DORA/private'; root.mkdir(parents=True)
            target=root/'future-work'; checked=[]
            for kind in ('owner','foreign','empty'):
                def acl(args,**kwargs):
                    checked.append(Path(kwargs['env']['DORA_PRIVATE_CHECK_PATH']))
                    identity=('[System.Security.Principal.WindowsIdentity]::GetCurrent().User' if kind=='owner'
                              else "[System.Security.Principal.SecurityIdentifier]::new('S-1-1-0')")
                    body=("[pscustomobject]@{Access=@([pscustomobject]@{AccessControlType='Allow';IdentityReference="+identity+"})}"
                          if kind!='empty' else '')
                    args=list(args); args[-1]='function Get-Acl { '+body+' }; '+args[-1]
                    return run(args,**kwargs)
                with self.subTest(kind=kind),patch.object(self.op.subprocess,'run',side_effect=acl):
                    if kind=='owner': self.op.require_private(target,Path(td)/'repo')
                    else:
                        with self.assertRaisesRegex(ValueError,'PRIVATE_STORAGE_ACL_INVALID'):
                            self.op.require_private(target,Path(td)/'repo')
            self.assertEqual([root]*3,checked); self.assertFalse(target.exists())

    def test_frozen_functions_reused(self):
        self.assertIs(self.op.v1.run_sequence,v1.run_sequence)
        for method in ('warmup','cleanup','partial','safety_evidence'):
            self.assertIs(getattr(self.op.SmallDriver,method),getattr(v1.SmallDriver,method))
        self.assertIs(self.op.c.evaluate,c.evaluate)
        self.assertEqual('217b5662bfd22520779a2df2551f553cb17e97e11f0273e8238682a5f4b7f69f',c.digest(c.profile()))

    def test_repository_head_branch_parent_dirty(self):
        op=self.op
        for kind in ('head','branch','parent','dirty'):
            def git(args,**kwargs):
                command=args[3:]
                value=('wrong' if kind=='head' else 'a'*40) if command==['rev-parse','HEAD'] else (
                    'wrong' if kind=='parent' else op.BASELINE_HEAD) if command==['rev-parse','HEAD^'] else (
                    'wrong' if kind=='branch' else op.BRANCH) if command==['branch','--show-current'] else (' M source' if kind=='dirty' else '')
                return subprocess.CompletedProcess(args,0,value.encode(),b'')
            with self.subTest(kind=kind),patch.object(op.subprocess,'run',side_effect=git), \
                 patch.object(Path,'read_bytes',side_effect=AssertionError('No file reads')),self.assertRaisesRegex(ValueError,'REPOSITORY'):
                op.verify_repository(Path('.'),'a'*40)

    def test_operator_hash_and_transitive_scope(self):
        op=self.op
        with tempfile.TemporaryDirectory() as td:
            repo=Path(td); files={}
            for name in op.OPERATOR_FILES:
                p=repo/name; p.parent.mkdir(parents=True,exist_ok=True); raw=('generated '+name).encode(); p.write_bytes(raw)
                files[name]={'bytes':len(raw),'sha256':sha(raw)}
            record={'operatorId':op.OPERATOR_ID,'operatorFiles':files,'operatorCanonicalSha256':c.digest(files),
                    'protectedHistoricalFiles':{},'evaluationProfileSha256':c.digest(c.profile())}
            evidence=repo/op.EVIDENCE_PATH; evidence.parent.mkdir(parents=True,exist_ok=True); evidence.write_bytes(c.canonical(record))
            def git(args,**kwargs):
                value='a'*40 if args[-1]=='HEAD' else op.BASELINE_HEAD if args[-1]=='HEAD^' else op.BRANCH if 'branch' in args else ''
                return subprocess.CompletedProcess(args,0,value.encode(),b'')
            with patch.object(op.subprocess,'run',side_effect=git):
                op.verify_repository(repo,'a'*40)
                (repo/'tools/run_alpha_asr_small_campaign.py').write_bytes(b'changed')
                with self.assertRaisesRegex(ValueError,'OPERATOR_FILE'): op.verify_repository(repo,'a'*40)


if __name__=='__main__': unittest.main()
